Implement aggregation
xaiinc/ainar pull request #27
Opened 2022-03-09 16:09 UTC by suttang

2022-03-15 09:32 UTC, odoku requested changes

2022-03-15 09:32 UTC, odoku commented on ainar/aggregates/__init__.py
> +    data_per_category = [_gather_category_data(category) for category in categories.prefetch(Annotation, Image)]
prefetchで取得しちゃうとフィルターしたアノテーションも取得出来ちゃうので集計結果がおかしくなる気がする。。

2022-03-23 06:26 UTC, suttang commented
```
$ python -m ainar annotations/instances_val2017.json --cache hogehoge.sqlite3 --filter
 "{\"classes\":[\"person\", \"bicycle\"]}"

{'per_class': {'person': {'images': 2693, 'boxes': 11004, 'boxes_per_size': {'0-10': 8556, '10-20': 1003, '20-30': 504, '30-40': 343, '40-50': 222, '50-60': 127, '60-70': 90, '70-80': 58, '80-90': 44, '90-100': 57}, 'boxes_per_image': 4.086149275900483}, 'bicycle': {'images': 149, 'boxes': 316, 'boxes_per_size': {'0-10': 275, '10-20': 16, '20-30': 9, '30-40': 6, '40-50': 5, '50-60': 2, '60-70': 0, '70-80': 2, '80-90': 0, '90-100': 1}, 'boxes_per_image': 2.120805369127517}}, 'total': {'num_classes': 2, 'images': 2720, 'boxes': 11320, 'boxes_per_size': {'0-10': 8831, '10-20': 1019, '20-30': 513, '30-40': 349, '40-50': 227, '50-60': 129, '60-70': 90, '70-80': 60, '80-90': 44, '90-100': 58}, 'boxes_per_image': 4.161764705882353}}
```

2022-03-23 06:28 UTC, odoku approved these changes
APO!!!

2022-03-23 06:28 UTC, merged